### ISSUE TITLE
you dont even deserve a star because you didnt try hard enough so heres a square 🟨 

### ISSUE THREAD

**Issue by 9xbt** [CrystalOSDevelopment/COSMOS-tutorial#1]
![image](https://github.com/CrystalOSDevelopment/COSMOS-tutorial/assets/109512837/f5f63836-70ea-4a94-9833-41cb89af5ef8)

**Comment by CrystalOSDevelopment** [comment]
So do you deserve a yellow square, because for sure you failed to express your problem.

**Comment by prescott2m** [comment]
bruh

**Comment by 9xbt** [comment]
xD i was just joking
but next time explain a bit better what you're doing instead of just writing the code and giving comments @CrystalOSDevelopment
